[package]
name = "gpui-base-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { version = "*" }
unicode-segmentation = "1.12"
ropey = "1.6"

[dev-dependencies]
gpui = { version = "*", features = ["test-support"] }
